import type { Metadata } from "next"
import "./globals.css"
import { ReactNode } from "react"
import { Poppins as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ViewTransitions } from "next-view-transitions"

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type LayoutProps = Readonly<{
  children: ReactNode
}>

export default function RootLayout({ children }: LayoutProps) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={cn(fontSans.variable)}>{children}</body>
      </html>
    </ViewTransitions>
  )
}
