import "./globals.css"

import type { Metadata } from "next"
import { Poppins as FontSans } from "next/font/google"
import { ViewTransitions } from "next-view-transitions"
import type { ReactNode } from "react"

import { cn } from "@/lib/utils"

import { Header } from "./Header"

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type RootLayoutProps = Readonly<{
  children: ReactNode
  searchParams?: unknown
}>

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={cn(fontSans.variable)}>
          <Header />
          {children}
        </body>
      </html>
    </ViewTransitions>
  )
}
